# Generated by Django 5.2.6 on 2025-09-07 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('descirption', models.TextField()),
                ('item_collection', models.CharField(choices=[('LIKE_NEW', 'Like New'), ('EXCELLENT', 'Excellen'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=25)),
                ('defects', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_price_range', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_price_range', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Confidence', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], default='MEDIUM', max_length=25)),
                ('dalivary_status', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='item_images', to='shops.imageuploded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_date', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('privecy_polycy_status', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='products_list', to='shops.product')),
            ],
        ),
    ]
